#!/usr/bin/env bash

command -v jq >/dev/null 2>&1 || {
  echo >&2 "Program 'jq' required but it is not installed.
Aborting."
  exit 1
}
command -v wget >/dev/null 2>&1 || {
  echo >&2 "Program 'wget' required but is not installed.
Aborting."
  exit 1
}

CITY="Piracicaba"
API_KEY="a547a1e984054494bfe20806240904"
URL="http://api.weatherapi.com/v1/current.json?key=${API_KEY}&q=${CITY}&aqi=no"

WEATHER_RESPONSE=$(wget -qO- "${URL}")

WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.current.condition.text' | sed 's/"//g')
WEATHER_TEMP=$(echo $WEATHER_RESPONSE | jq '.current.temp_c')
WIND_DIR=$(echo "$WEATHER_RESPONSE" | jq '.current.wind_dir')
WIND_SPEED=$(echo "$WEATHER_RESPONSE" | jq '.current.wind_kph')

WIND_SPEED=$(awk "BEGIN {print 60*60*$WIND_SPEED/1000}")
WIND_DIR=$(awk "BEGIN {print int(($WIND_DIR % 360)/22.5)}")
DIR_ARRAY=(N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N)
WIND_DIR=${DIR_ARRAY[WIND_DIR]}

echo "${WEATHER_CONDITION} ${WEATHER_TEMP}°C"
